### ISSUE TITLE
Мультиселект

### ISSUE THREAD

**Issue by 6jlarogap** [6jlarogap/blagodarie-site#2]
- [ ] добавить прячущуюся и выползающую при скроле панель меню - высотой с кнопку обновить (чтобы нажимать с телефона) - в неё поместить название, мультиселект и кнопку "обновить"
- [ ] показать на графиках и карте только выбранные ощущения
- [ ] сохранить статус в куках

**Comment by suprune20** [comment]
Все эти работы с понедельника. Все равно до выходных не успею, а еще одни выходные я себе портить не собираюсь. За эти  два дня доделаю апи, чтобы у Сергея была работа, т.к. понедельник у меня традиционно очень занят основной работой.

**Comment by 6jlarogap** [comment]
Это я потестил систему проектов на гитхабе - думаю туда в публичное
пространство переехать. Выходные - вне оспасности!! )))

ср, 29 апр. 2020 г., 9:17 Eugene Suprun <notifications@github.com>:

**Comment by 6jlarogap** [comment]
Можно использовать например такой https://www.jqueryscript.net/demo/jQuery-Plugin-For-Selecting-Multiple-Elements-Multiple-Select/

Но лучше сразу, исходя из того что у нас будет древовидная структура симптомов - https://www.jqueryscript.net/demo/jQuery-Plugin-For-Multi-Selectable-Tree-Structure-Tree-Multiselect/
